runtime: python27
api_version: 1
threadsafe: true

libraries:
 - name: pycrypto
   version: "2.6"

builtins:
- remote_api: on
- appstats: on

handlers:
- url: /javascript
  static_dir: javascript

- url: /stylesheets
  static_dir: stylesheets

- url: /process_allowance_schedules
  script: allowancebank.application
  login: admin
  secure: always

- url: /.*
  script: allowancebank.application
  secure: always
